name: Testing

on:
  push:
  workflow_dispatch:

env:
  PIP_NO_OPTION: on
  PIP_NO_CLEAN: on
  PIP_PREFER_BINARY: on

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      neo4j:
        image: neo4j:5.9-community
        env:
          NEO4J_AUTH: neo4j/password
        ports:
          - 7687:7687

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache requirements
        uses: actions/cache@v3
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Cache poetry
        uses: actions/cache@v3
        env:
          cache-name: cache-poetry
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: make install

      - name: Run test suite
        run: make pytest
